### ISSUE TITLE
DNA feature dimension

### ISSUE THREAD

**Issue by misaki-taro** [BioMedicalBigDataMiningLab/PHIAF#2]
Hi, 

Thanks for providing PHIAF.

I used the script of computing dna features but only got 270 dimensions features for each phage
![图片](https://user-images.githubusercontent.com/80313531/164581086-5de758d3-5e84-472d-8d75-7023150cf477.png)

Best,
Misaki

**Comment by mengluli-web** [comment]
Hi, 

When you use iLearn to compute the DNA features, you should set the parameters k of Kmer and RCKmer as 3, not 2 (the default is 2).

Best,
Menglu Li

**Comment by misaki-taro** [comment]
Thank you~
